name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    name: "Deploy to prod"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_rsa.key
          chmod 600 ~/.ssh/id_rsa.key
          cat >> ~/.ssh/config << EOF
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/id_rsa.key
            StrictHostKeyChecking no
          EOF
        env:
          SSH_USER: ${{ secrets.USERNAME }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.HOST }}

      - name: Check out the source
        run: ssh staging 'cd personal/spending && git fetch && git reset --hard origin/main'

      - name: Build Front end
        if: ${{ always() }}
        run: ssh staging 'cd personal/spending/spending && npm i && npm run build'
      
      - name: Stop the server
        run: ssh staging 'screen -XS spending quit'
        
      - name: Start the server
        if: ${{ always() }}
        run: ssh staging 'cd personal/spending/BackEnd/ && screen -dmS spending python3 main.py'
